export const AUTH = {
  LOGIN: {
    REQUEST: 'AUTH.LOGIN.REQUEST',
    SUCCESS: 'AUTH.LOGIN.SUCCESS',
    FAILURE: 'AUTH.LOGIN.FAILURE',
  },
};

export const PRODUCTS = {
  FETCH: {
    REQUEST: 'PRODUCTS.FETCH.REQUEST',
    SUCCESS: 'PRODUCTS.FETCH.SUCCESS',
    FAILURE: 'PRODUCTS.FETCH.FAILURE',
  },
};
